### ISSUE TITLE
FeatureSchema is rasing error when properties field is not empty

### ISSUE THREAD

**Issue by AdoniasAlcantara** [folt/marshmallow-geojson#26]
Given the example below:

```python
from marshmallow_geojson import FeatureSchema

data = {
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}

schema = FeatureSchema().load(data)
```

results in `marshmallow.exceptions.ValidationError: {'properties': {'name': ['Unknown field.']}}`.

The expected behavior is that no error is thrown.

**Comment by folt** [comment]
The rfc7946 standard does not uniquely define a 'properties' field.

[A Feature object has a member with the name "properties".  The value of the properties member is an object (any JSON object or a JSON null value).](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2)

```
class FeatureSchema(BaseSchema):
    type = Str(
        required=True,
        validate=OneOf(
            [FEATURE],
            error='Invalid feature type'
        )
    )

    geometry = Nested(
        GeometriesSchema,
        required=True,
    )

    properties = Nested(
        PropertiesSchema,
        required=True,
    )
```

```
class PropertiesSchema(BaseSchema):
    pass
```

To solve your problem, I propose to extend the FeatureSchema class, where you can specify a custom schema for properties.

```
MyPropertiesSchema(PropertiesSchema)
    name = Str(required=True)


class MyFeatureSchema(FeatureSchema):
    properties = Nested(
        MyPropertiesSchema,
        required=True,
    )
```

Maybe you should add this to the use cases?

**Comment by AdoniasAlcantara** [comment]
Sorry for the delay to reply. 

What I was trying to say is that marshmallow was throwing validation error when properties is different from an empty dictionary. I managed to get around the validation error by extending `FeatureSchema` as you mentioned, but maybe it would be appropriate that the default `FeatureSchema` implementation looks something like this:

```python
class FeatureSchema(BaseSchema):
    type = Str(
        required=True,
        validate=OneOf(
            [FEATURE],
            error='Invalid feature type'
        )
    )

    geometry = Nested(
        GeometriesSchema,
        required=True,
    )

    # Using a dict here
    properties = Dict(
        required=True
    )
```
I think such a change would not violate rfc 7946 and so we could use the schema without the need to extend it.
