### ISSUE TITLE
Is lack of "dump()" support intentional?

### ISSUE THREAD

**Issue by mparent61** [folt/marshmallow-geojson#43]
We're using this library with `flask-smorest` (and `marshmallow` of course!), and quite impressed with the out-of-the-box support for GeoJSON.

We did run into a big surprise though, as it appears that these schemas only implement the `load`/`loads` interfaces (with the fancy sub-schema selector logic), and do not implement the corresponding `dump` functionality. When we call `.dump()` with a `GeoJSONSchema` object, it just returns an empty dictionary (via the base Marshmallow `schema` method).

So I'm wondering if I'm missing something (being new to the `marshmallow` ecosystem), or perhaps `dump` wasn't the needed for the original use-case?

As an aside, I cobbled this together to simulate a proper `dump` method, while still leveraging this library's dynamic schema handling:
```
class GeoJsonSchema(marshmallow_geojson.GeoJSONSchema):

    def dump(self, obj: typing.Any, *, many: bool | None = None):
        # Do a JSON dance to convert Python-ized JSON to proper JSON
        return json.loads(
            json.dumps(
                # This is the interface supported by library. It returns a Python-ized JSON dictionary
                self.load(obj, many=many)
            )
        )
```

So wondering if anyone else has run into this before, or has advice? 

It does seem like it may be straightforward to build out the `dump` methods following the `load` patterns.

**Comment by folt** [comment]
Hi. Good point. In my practice, I usually needed to load GeoJSONS data, do validation and put it in the database. The suggestion to implement dump looks interesting. I will not be happy if you offer a pull requests.

**Comment by mparent61** [comment]
@folt wow, you beat me to it! I was still setting up my virtual environment :)
I've confirmed that this addresses my needs! Thank you very much :)
