### ISSUE TITLE
Proposal: Add examples to each GeoJSON type schema for OpenAPI doc support

### ISSUE THREAD

**Issue by spra85** [folt/marshmallow-geojson#50]
Currently, if using this library and trying to tie into existing Marshmallow tooling support for OpenAPI spec the docs come through for instance like this: 

<img width="310" alt="image" src="https://github.com/folt/marshmallow-geojson/assets/423943/d572bb67-088b-4972-af37-f5828a5c8d4a">

This can be alleviated by using the `example` key and passing in `metadata` for a Marshmallow field. One suggestion would be to take the existing pytest fixtures (Example: https://github.com/folt/marshmallow-geojson/blob/master/tests/conftest.py#L160) and move each GeoJSON type to a constant, and then re-using the constant in both the fixture and to generate the example. Would be something like the below (if this is an acceptable solution, I can put together a PR), see `metadata=dict(example=MULTIPOLYGON),`:

Constant:

```python
MULTIPOLYGON = {
        'type': 'MultiPolygon',
        'coordinates': [
            [
                [
                    [107, 7],
                    [108, 7],
                    [108, 8],
                    [107, 8],
                    [107, 7]
                ]
            ],
            [
                [
                    [100, 0],
                    [101, 0],
                    [101, 1],
                    [100, 1],
                    [100, 0]
                ]
            ]
        ]
    }
```

Example in MultiPolygon Schema:

```python
class MultiPolygonSchema(BaseSchema):
    type = Str(
        required=True,
        validate=OneOf(
            [MULTI_POLYGON],
            error='Invalid multi polygon type',
        )
    )

    coordinates = List(
        List(
            List(
                Tuple([lon, lat], required=True),
                required=True,
            ),
            required=True,
        ),
        required=True,
        metadata=dict(example=MULTIPOLYGON),
    )
```

**Comment by folt** [comment]
good offer, feel free to contribute
